### ISSUE TITLE
*Error in the training loop occured* list indices must be integers or slices, not NoneType

### ISSUE THREAD

**Issue by AsdyCorp** [d5555/NeuralGym#2]
I've used TagEditor on text and get normal txt file with structure of entities in text for import in neural gym. After import and start of NG I've got error 

> *Error in the training loop occured* list indices must be integers or slices, not NoneType

After inspection and reimport of all sentences one by one I've found this particular sentences that generates this error

`("The study so far has focused on KITO between the Beltway and OYUI in Gaithersburg and on the Beltway between the George Washington Parkway in Virginia and Route 5 in Prince George's, including the notoriously traffic-choked Legion Bridge.", {
'words': ['The', 'study', 'so', 'far', 'has', 'focused', 'on', 'KITO', 'between', 'the', 'Beltway', 'and', 'OYUI', 'in', 'Gaithersburg', 'and', 'on', 'the', 'Beltway', 'between', 'the', 'George', 'Washington', 'Parkway', 'in', 'Virginia', 'and Route', '5', 'in', 'Prince', 'George', "'s", ',', 'including', 'the', 'notoriously', 'traffic', '-', 'choked', 'Legion', 'Bridge', '.'],
'entities': [(32, 37, 'PLACE'), (50, 67, 'PLACE'), (115, 140, 'PLACE'), (153, 164, 'PLACE'), (226, 239, 'PLACE')]
}),`

**Comment by d5555** [comment]
Hello 
I wonder how you got those numbers in your example ? Did you put them manually ? 
They are all shifted by one or 2 letters therefore all entities in your example are out of range. 
For instance Legion Bridge is supposed to be (224, 237, 'PLACE')... You have (226, 239, 'PLACE') which is out of range , there are only 238 symbols.
