### ISSUE TITLE
I can't use NeuralGYM

### ISSUE THREAD

**Issue by StraigenDaigen** [d5555/NeuralGym#3]
How can I use this tool inside anaconda environment, because when I'm executing directly in windows, I received the following error: 

> spaCy2.2.4
Variables initialization...
Output_dir:"D:/Steven/TRABAJO_CK/AMI/OCR_Codigos/opencv-text-recognition/pruebas/"
Creating blank 'en' model
Loading training data...
TRAIN_DATA loaded from path: "D:\Steven\TRABAJO_CK\AMI\OCR_Codigos\opencv-text-recognition\pruebas\TOOL.txt"
Number of examples: 2
n_iter  =  100
learn_rate  =  0.001
drop  =  0.2
batch_start  =  4.0
batch_stop  =  32.0
batch_compound  =  1.001
Selected pipeline components: ['tagger', 'parser', 'ner', 'textcat']
Initializing variables error:
'str' object has no attribute 'get'
spaCy2.2.4
Variables initialization...
Output_dir:"D:/Steven/TRABAJO_CK/AMI/OCR_Codigos/opencv-text-recognition/pruebas/"
Creating blank 'en' model
Loading training data...
TRAIN_DATA loaded from path: "D:\Steven\TRABAJO_CK\AMI\OCR_Codigos\opencv-text-recognition\pruebas\TOOL.txt"
Number of examples: 2
n_iter  =  100
learn_rate  =  0.001
drop  =  0.2
batch_start  =  4.0
batch_stop  =  32.0
batch_compound  =  1.001
Selected pipeline components: ['ner']
Initializing variables error:
'str' object has no attribute 'get'

It could be helpful if you can help.

**Comment by d5555** [comment]
Were you using the compiled version (Option 1)  or python version (Option 2)  of the tool ? 
Also what is your python version ?
